models/adocao.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from database import Base  # use o mesmo Base dos outros models

class Adocao(Base):
    __tablename__ = "adocoes"

    id = Column(Integer, primary_key=True, autoincrement=True)

    usuario_id = Column(Integer, ForeignKey("usuarios.id"), nullable=False)
    animal_id = Column(Integer, ForeignKey("animais.id"), nullable=False)

    status = Column(String, default="pendente")  
    # opções possíveis: pendente, aprovado, recusado, concluido

    # RELACIONAMENTOS
    usuario = relationship("Usuario")
    animal = relationship("Animal")

    def __repr__(self):
        return f"<Adocao usuario={self.usuario_id} animal={self.animal_id}>"

models/interesse.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from database import Base

class Interesse(Base):
    __tablename__ = 'interesses'
    id = Column(Integer, primary_key=True)
    usuario_id = Column(Integer, ForeignKey('usuarios.id'), nullable=False)
    animal_id = Column(Integer, ForeignKey('animais.id'), nullable=False)
    status = Column(String(20), default='pendente')

    usuario = relationship("Usuario")
    animal = relationship("Animal")

    def __repr__(self):
        return f"<Interesse usuario_id={self.usuario_id} animal_id={self.animal_id} status={self.status}>"

controllers/adocao_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from sqlalchemy.orm import joinedload
from database import Sessao_base
from models.adocao import Adocao

adocao_bp = Blueprint("adocao", __name__)

@adocao_bp.route('/animais_adocoes_usuario')
def animais_adocoes_usuario():
    usuario_id = session.get('usuario_id')

    if not usuario_id:
        return redirect(url_for('auth.login'))

    with Sessao_base() as sessao:
        adocoes = sessao.query(Adocao)\
            .options(joinedload(Adocao.animal))\
            .filter_by(usuario_id=usuario_id)\
            .all()

    return render_template('adocao.html', adocoes=adocoes)

@adocao_bp.route('/adotar/<int:animal_id>', methods=['POST'])
def adotar(animal_id):
    usuario_id = session.get('usuario_id')

    if not usuario_id:
        return redirect(url_for('auth.login'))

    with Sessao_base() as sessao:
        nova_adocao = Adocao(usuario_id=usuario_id, animal_id=animal_id)
        sessao.add(nova_adocao)
        sessao.commit()

    flash("Adoção solicitada com sucesso!", "success")
    return redirect(url_for('adocao.animais_adocoes_usuario'))

controllers/animais_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from database import Sessao_base
from models.animal import Animal
from models.interesse import Interesse
from models.adocao import Adocao
import os 
from werkzeug.utils import secure_filename
animais_bp = Blueprint("animais", __name__)
# animais_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from database import Sessao_base
from models.animal import Animal
from models.interesse import Interesse
from models.adocao import Adocao

animais_bp = Blueprint("animais", __name__)

@animais_bp.route('/', methods=['GET'])
def animais():
    with Sessao_base() as sessao:
        animais = sessao.query(Animal).all()
    return render_template('animais.html', animais=animais)


@animais_bp.route('/detalhes_animal/<int:animal_id>', methods=['GET'])
def detalhes_animal(animal_id):
    with Sessao_base() as sessao:
        animal = sessao.query(Animal).get(animal_id)
    return render_template('detalhes_animal.html', animal=animal)


@animais_bp.route('/cadastrar_animal', methods=['GET', 'POST'])
def cadastrar_animal():
    if request.method == 'POST':
        nome = request.form['nome_form']
        raca = request.form['raca_form']
        idade = int(request.form['idade_form'])
        sexo = request.form['sexo_form']
        porte = request.form['porte_form']
        vacinado = request.form.get('vacinado_form') == 'on'
        vacinas_tomadas = request.form['vacinas_tomadas_form']
        sobre = request.form['sobre_form']
        localizacao = request.form['localizacao_form']
        nome_protetor = request.form['nome_protetor_form']
        telefone_contato = request.form['telefone_contato_form']
        email_contato = request.form['email_contato_form']
        foto_animal = request.form['foto_form']

        animal = Animal(
            nome=nome, raca=raca, idade=idade, sexo=sexo, porte=porte,
            vacinado=vacinado, vacinas_tomadas=vacinas_tomadas, sobre=sobre,
            localizacao=localizacao, nome_protetor=nome_protetor,
            telefone_contato=telefone_contato, email_contato=email_contato,
            foto=foto_animal
        )

        with Sessao_base() as sessao:
            sessao.add(animal)
            sessao.commit()

        flash("Animal cadastrado com sucesso!", "success")
        return redirect(url_for('animais.animais_para_adocao'))

    return render_template('cadastrar_animal.html')


@animais_bp.route('/animais_para_adocao', methods=['GET'])
def animais_para_adocao():
    with Sessao_base() as sessao:
        animais = sessao.query(Animal).all()
    return render_template('adocao.html', animais=animais)


@animais_bp.route('/ver_animal/<int:animal_id>', methods=['GET', 'POST'])
def ver_animal(animal_id):

    # Verificar login
    if 'usuario_id' not in session:
        flash("Faça login para continuar.", "warning")
        return redirect(url_for('auth.login'))

    with Sessao_base() as sessao:
        animal = sessao.query(Animal).filter_by(id=animal_id).first()

        if not animal:
            flash("Animal não encontrado.", "danger")
            return redirect(url_for('animais.animais'))

        # Quando o usuário apertar um botão
        if request.method == 'POST':
            acao = request.form.get("acao")

            # --- LISTA DE INTERESSE ---
            if acao == "interesse":
                existe = sessao.query(Interesse).filter_by(
                    usuario_id=session['usuario_id'],
                    animal_id=animal.id
                ).first()

                if existe:
                    flash("Este animal já está nos seus interesses.", "info")
                else:
                    novo = Interesse(
                        usuario_id=session['usuario_id'],
                        animal_id=animal.id
                    )
                    sessao.add(novo)
                    sessao.commit()
                    flash("Animal adicionado aos seus interesses!", "success")

                return redirect(url_for('interesse.interesse'))

            # --- ADOÇÃO ---
            if acao == "adotar":
                existe = sessao.query(Adocao).filter_by(
                    usuario_id=session['usuario_id'],
                    animal_id=animal.id
                ).first()

                if existe:
                    flash("Você já solicitou adoção deste animal.", "info")
                else:
                    nova = Adocao(
                        usuario_id=session['usuario_id'],
                        animal_id=animal.id,
                        status="pendente"
                    )
                    sessao.add(nova)
                    sessao.commit()
                    flash("Adoção solicitada!", "success")

                return redirect(url_for('adocao.animais_adocoes_usuario'))

    # GET → página do animal
    return render_template('detalhes_animal.html', animal=animal)

controllers/interesse_controller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from database import Sessao_base
from models.interesse import Interesse
from models.usuario import Usuario
from models.animal import Animal

interesse_bp = Blueprint("interesse", __name__)

# Página para solicitar adoção de um animal
@interesse_bp.route('/interesse/<int:animal_id>', methods=['GET', 'POST'])
def interesse(animal_id):
    if 'usuario_id' not in session:
        flash("Você precisa estar logado para adotar.", "warning")
        return redirect(url_for('auth.login'))

    with Sessao_base() as sessao:
        animal = sessao.query(Animal).filter(Animal.id == animal_id).first()
        if not animal:
            flash("Animal não encontrado.", "danger")
            return redirect(url_for('animais.animais'))

        if request.method == 'POST':
            endereco = request.form['endereco_form']

            interesse = Interesse(
                usuario_id=session['usuario_id'],
                animal_id=animal.id,
                endereco=endereco,
            )
            sessao.add(interesse)
            sessao.commit()

            flash("Interesse de adoção arquivado!.", "success")
            return redirect(url_for('animais.animais'))

    return render_template('interesse.html', animal=animal)

templates/adocao.html
{% extends 'base.html' %}

{% block titulo %}Adoções{% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">{% endblock %}

{% block conteudo %}

<h1>ADOÇÕES</h1>

<div class="container">
<div class="animais">
    {% for adocao in adocoes %}
    <div class="animal-card">
        <img src="{{ adocao.animal.foto }}">
        <h3>{{ adocao.animal.nome }}</h3>
        <p>{{ adocao.animal.raca }}</p>
        <p>{{ adocao.animal.idade }} anos</p>
    </div>
    {% endfor %}
</div>
</div>

{% endblock %}

templates/animais.html
{% extends 'base.html'%}
{% block titulo %} animais {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">{% endblock %}

{% block conteudo %}

<h1>é pra exibir os animais</h1>
    <div class="animais">
       {% for animal in animais %}
       
        <a class="card_link" href="{{ url_for('animais.detalhes_animal', animal_id=animal.id) }}">          
            <div class="animal-card">

                <div class="foto-animal">
                    <img src="{{ animal.foto }}" alt="">
                </div>
                
                <div class="info-animal">
                <h3>{{ animal.nome }}</h3>
                <p>Raça: {{ animal.raca }}</p>
                <p>Idade: {{ animal.idade }} anos</p>
                <p>Localização: {{ animal.localizacao }} anos</p> 
                </div>
            </div>
        </a>
        {% endfor %} 
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} {% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}?v=2">
    <link rel="stylesheet" href="{{ url_for('static', filename='menu.css') }}">

    {% block extra_css %}{% endblock %}

<body>
    {% include 'componentes/menu.html' %}
    {% block conteudo %}

    {% endblock %}

</body>
</html>

templates/cadastrar_animal.html
{% extends 'base.html'%}
{% block titulo %} Formulário {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='cadastro_animal.css') }}">{% endblock %}

{% block conteudo %}

<div class="container";>
    <div class="img">
        <img src="../static/img/1-adocao.jpg" alt="">
    </div>
    <form action="{{ url_for('animais.cadastrar_animal') }}" method="POST">
        <h1 style="margin-top: 1px; margin-bottom: 1px;">Coloque-me para adoção!</h1>
        Nome: <input type="text" name="nome_form">
        Raça: <input type="text" name="raca_form">
        <div class="linha">
            Idade: <input type="number" name="idade_form">
            Sexo: <input type="text" name="sexo_form"> 
            Porte: <input type="text" name="porte_form">
        </div>
        <div class="linha">
        Vacinado? <input type="checkbox" name="vacinado_form">
        Vacinas tomadas: <input type="text" name="vacinas_tomadas_form">
        </div>
        Sobre: <input type="text" name="sobre_form">
        Foto (Link para uma foto do animal): <input type="text" name="foto_form">
        Localização: <input type="text" name="localizacao_form">
        <div class="linha">
            Nome do protetor: <input type="text" name="nome_protetor_form">
            Telefone para contato: <input type="text" name="telefone_contato_form">
        </div>
        Email contato: <input type="text" name="email_contato_form">
        <input type="submit" value="Enviar">
    </form>
    </div>

{% endblock %}

templates/cadastro.html
{% extends 'base.html'%}
{% block titulo %} Formulário {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='cadastro.css') }}">{% endblock %}
{% block conteudo %}

<div class="container">
    <form action="" method="post">
        <h1>Formulário de Cadastro</h1>
        Nome <input type="text" name="nome_form">
        Nome completo <input type="text" name="nome_completo_form">
        <div class="linha">
            Telefone para contato <input type="text" name="telefone_form">
            Email <input type="email" name="email_form"> 
        </div>       
        Senha <input type="password" name="senha_form">
        <div class="linha">
            Rua <input type="text" name="rua_form">
            Bairro <input type="text" name="bairro_form">
        </div>
        <div class="linha">
            Cidade <input type="text" name="cidade_form">
            Numero <input type="text" name="numero_form">
        </div>
        <div class="linha">
            Complemento <input type="text" name="complemento_form">
            Estado <input type="text" name="estado_form">
        </div>
        <input type="submit" value="Enviar">
    </form>
    <div class="img">
        <img src="../static/img/mulher com cachorro.png" alt="">
    </div>

</div>


{% endblock %}

templates/contatos.html
{% extends 'base.html'%}
{% block titulo %} Contatos {% endblock %}

{% block conteudo %}



{% endblock %}

templates/detalhes_animal.html
{% extends 'base.html'%}
{% block titulo %} Formulário {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='cadastro_animal.css') }}">{% endblock %}

{% block conteudo %}

<div class="container" style="width: 100%;">
    <div class="img">
        <div class="foto-animal">
            <img src="{{ animal.foto }}" alt="">
        </div>
    </div>
    <form action="{{ url_for('animais.detalhes_animal', animal_id=animal.id) }}" method="GET">
        <h1 style="margin-top: 1px; margin-bottom: 1px;">Coloque-me para adoção!</h1>
        Nome: <input type="text" value="{{ animal.nome }}" readonly style="pointer-events: none;">
        Raça: <input type="text" value="{{ animal.raca }}" readonly style="pointer-events: none;">
        <div class="linha">
            Idade: <input type="text" value="{{ animal.idade }}" readonly style="pointer-events: none;">
            Sexo: <input type="text" value="{{ animal.sexo }}" readonly style="pointer-events: none;">
            Porte: <input type="text" value="{{ animal.porte }}" readonly style="pointer-events: none;">
        </div>
        <div class="linha">
        Vacinado? <input type="text" value="{{ animal.vacinado }}" readonly style="pointer-events: none;">
        Vacinas tomadas: <input type="text" value="{{ animal.vacinas_tomadas }}" readonly style="pointer-events: none;">
        </div>
        Sobre: <input type="text" value="{{ animal.sobre }}" readonly style="pointer-events: none;">
        Localização: <input type="text" value="{{ animal.localizacao }}" readonly style="pointer-events: none;">
        <div class="linha">
            Nome do protetor: <input type="text" value="{{ animal.nome_protetor }}" readonly style="pointer-events: none;">
            Telefone para contato: <input type="text" value="{{ animal.telefone_contato }}" readonly style="pointer-events: none;">
        </div>
        Email contato: <input type="text" value="{{ animal.email_contato }}" readonly style="pointer-events: none;">
        
    </form>
    <form action="{{ url_for('adocao.adotar', animal_id=animal.id) }}" method="POST">
    <button type="submit" style="color:white; background:brown;">
        ADOTAR AGORA
    </button>
    </form>

        <!-- <form method="POST">
            <input type="hidden" name="acao" value="interesse">
            <button type="submit" style="color:white; background:blue;">
            ANIMAIS DE INTERESSE
            </button>
        </form> -->
</div>

{% endblock %}

templates/index.html
{% extends 'base.html'%}
{% block titulo %} Index {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">{% endblock %}

{% block conteudo %}
<div class="img">
        <img src="../static/img/cachorrro-e-gato.svg" alt="">
    </div>
<div class="container">
    <h1 class="titulo1">ANIMAIS PARA ADOÇÃO</h1>
    <div class="animais">
       {% for animal in animais %}
            <div class="animal-card">
                <div class="foto-animal">
                    <div class="imagem-animal">
                        <img src="{{ animal.foto }}" alt="">
                    </div>
                </div>

                <div class="info-animal">
                <h3>{{ animal.nome }}</h3>
                <p>Raça: {{ animal.raca }}</p>
                <p>Idade: {{ animal.idade }} anos</p>
                <p>Localização: {{ animal.localizacao }} anos</p> 
                </div>
            </div>
        </a>
        {% endfor %} 
    </div>
    
</div>

{% endblock %}

templates/interesse.html
{% extends 'base.html'%}
{% block titulo %} Interesses {% endblock %}

{% block conteudo %}
<h1>MEUS ANIMAIS DE INTERESSE</h1>

{% for animal in animais %}
  <div class="animal-card">
    <h3>{{ animal.nome }}</h3>
    <p>Raça: {{ animal.raca }}</p>
    <p>Idade: {{ animal.idade }} anos</p>
    <p>Localização: {{ animal.localizacao }}</p>
  </div>
{% endfor %}

{% endblock %}

templates/login.html
{% extends 'base.html'%}
{% block titulo %} login {% endblock %}
{% block extra_css %}<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">{% endblock %}

{% block conteudo %}
    
<div class="container">
        <form action="{{url_for('auth.login')}}" method="post">
        <h1>Faça Login</h1>
        Email: <input type="email" name="email_form">
        Senha: <input type="password" name="senha_form">
        <input type="submit" value="Enviar">
        {% if erro %}
            <div class="erro">{{ erro }}</div>
        {% endif %}
        </form>
        <div class="img">
            <img src="../static/img/cachorrinho.png" alt="">
        </div>
</div>
{% endblock %}

templates/perfil.html
{% extends 'base.html'%}
{% block titulo %} perfil {% endblock %}

{% block conteudo %}

<label><h2>{{usuario.nome}}</h2></label>

{% endblock %}

templates/sobre.html
{% extends 'base.html'%}
{% block titulo %} sobre {% endblock %}

{% block conteudo %}

<h1>Página Sobre</h1>

{% endblock %}